name: Geltona-MLpipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt 
      
      - name: Copy .cdsapirc to home directory
        run: cp Data_Processing/.cdsapirc ~/.cdsapirc
      
    # - name: CO2.py
      #  working-directory: Data_Processing
      #  run: python CO2.py 
       # env:
        #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB }} 

      - name: CH4.py
        working-directory: Data_Processing
        run: python CH4.py 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          
          
          
